# Generated by Django 3.2.9 on 2023-02-12 17:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_auto_20230210_1252'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='currency',
            field=models.CharField(choices=[('eur', 'EURO'), ('usd', 'USD')], default='eur', max_length=12, verbose_name='Currency'),
        ),
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.5)]),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(choices=[('eur', 'EURO'), ('usd', 'USD')], default='eur', max_length=12, verbose_name='currency')),
                ('items', models.ManyToManyField(related_name='orders', to='payments.Item', verbose_name='Item list')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'default_related_name': 'orders',
            },
        ),
    ]
